Sprint 3
isavlex-n/middle.messenger.praktikum.yandex pull request #3
Opened 2022-04-28 10:42 UTC by isavlex-n

Привет! Отправляю проект на проверку.

2022-04-28 17:48 UTC, agadoev requested changes
Привет! Спасибо за работу
Обрати внимание на следующие моменты:
1) Часто ты вызываешь асинхронные функции синхронно
2) Много ненужного закомментрованного кода
3) Разберись с внедрением зависимостей в классы. Я оставил комментарий.
4) Не при каждом вызове api есть обработка исключений

Поправь эти моменты и двинемся дальше :)

2022-04-28 17:48 UTC, agadoev commented on src/pages/chats/chats.ts
>      if (!message.value) {
тут может выскочить ошибка "cannot read properies of null"
Лушче проверить на null сначала message, а потом message.value
if (!message || !message.value) {...}

2022-04-28 17:48 UTC, agadoev commented on src/api/baseAPI.ts
> +  update() {
update не должен принимать в себя какие-то данные, которые нужно обновить?

2022-04-28 17:48 UTC, agadoev commented on src/core/utils.ts
> +  const root = document.querySelector(query as string);
querySelector может вернуть null, если не найдет элемент по селектору. Лучше эту ситуацию обработать явно:
if (!root) {
  ... 
}

2022-04-28 17:48 UTC, agadoev commented on src/api/loginAPI.ts
> +export type LoginRequestData = {
Я заметил, что у тебя есть файл types.ts, где скорее всего должны храниться типы. Это хорошая идея, и если ты выбрал такой способ организации типов, то стоит его придерживаться и хранить типы там. Поэтому с точки зрения организации кода будет правильнее перенести типы туда

2022-04-28 17:48 UTC, agadoev commented on src/pages/login/login.ts
> +    service.login(loginData)
метод login асинхронный и его нужно вызывать через await. Но тогда нужно так же метод submitHandler сделать асинхронным

2022-04-28 17:48 UTC, agadoev commented on src/pages/signup/signup.ts
> +    service.signup(loginData)
Нужно вызывать через await, так же, как и login()

2022-04-28 17:48 UTC, agadoev commented on src/services/userLogin.ts
> +const loginApi = new LoginAPI()
Сейчас класс UserLoginService зависит от глобальной переменной loginApi. Вообще, зависить от глобальных переменных - довольно плохая пракика, т.к. если другой разработчик в комнаде случайно изменит переменную loginApi, то класс UserLoginService будет работать непредсказуемо, скорее всего будут ошибки. 

Существует целая тема про внедрение зависимостей, можешь почитать тут
https://habr.com/ru/post/528890/

Хорошей практикой является внедрение зависимости через параметры конструктора, но на этом проекте можно просто создавать внутри конструктора инстанс объекта через new и присвоить его приватному пою класса

2022-04-28 17:48 UTC, agadoev commented on src/services/userLogin.ts
> +      // const userRequest = loginApi.getUserData()
Лишние комментарии лучше убирать, а то они загрязняют код.

2022-04-28 17:48 UTC, agadoev commented on src/services/userSignup.ts
> +        setTimeout(() => {
Действительно ли тут нужен этот setTimeout?

2022-04-28 17:48 UTC, agadoev commented on src/utils/queryStringify.ts
> +export default function queryStringify(data: Indexed): string {
Сейчас этот код довольно сложно понять. Эту функцию точно можно написать чище и понятнее. Вроде у тебя в файле HTTPTransport есть еще одна реализация функции queryStringify(), она будет почище

2022-04-28 17:48 UTC, agadoev commented on src/services/auth.ts
> +    await auth.logout()
Тут стоит обработать возможные ошибки от сервера с помощью try {} catch {}

2022-04-28 17:48 UTC, agadoev commented on src/components/modal/modal.ts
> +    if (type === 'add-user') {
Нужно стараться избегать таких строковых литералов в коде. Тому есть две причины:
1) Можно просто ошибиться в написании и не заметить
2) Если нужно изменить строку, то придется бегать по всем местам в коде, где она используется

Предлагаю вынести ее и другие подобные строковые литералы в строковые константы, названные в UPPER_CASE, либо же в enum

2022-04-28 17:48 UTC, agadoev commented on src/pages/chats/chats.ts
> +    const input = document.querySelector<HTMLInputElement>(
querySelector может вернуть null, поэтому нужно добавить проверку на null

2022-04-28 17:48 UTC, agadoev commented on src/pages/profile/profile.ts
> +        userService.changeUserProfile({
Этот метод асинхронный, поэтому вызывать его нужно через await. Тогда и  setTimeout(..., 2000) не понадобится

2022-04-28 17:48 UTC, agadoev commented on src/pages/profile/profile.ts
> +        userService.changeUserPassword({
то же самое, что и с changeUserProfile

2022-04-28 17:48 UTC, agadoev commented on src/pages/profile/profile.ts
> +    userService.changeUserAvatar(formData).then((data) => {
Тоже нужно вызывать через await. И не стоит забывать обрабатывать исключения. Что будет, если сервер вернет 500 ошибку? В таком случае нужно перехватить эту ошибку в блоке catch {} и вывести пользователю сообщение об ошибке

2022-04-28 17:48 UTC, agadoev commented on src/core/Router.test.ts
> +  router
В целом неплохие тесты, однако есть один важный момент. Сейчас каждый тест работает с глобальным объектом роутер, значит если один тест изменил этот объект, то в следующем тесте этот объет будет уже измененным. Это не есть хорошо, потому что один тест нарушает состояние другого теста
Тесты должны быть изолированы и не влиять на состояния друг друга
Чтобы это обеспечить, можно использовать фикстуры beforeEach, и там создавать объект роутера, чтобы для каждого теста создавался свой, новый объект

2022-04-29 16:35 UTC, isavlex-n commented
> Привет! Спасибо за работу Обрати внимание на следующие моменты:
> 
> 1. Часто ты вызываешь асинхронные функции синхронно
> 2. Много ненужного закомментрованного кода
> 3. Разберись с внедрением зависимостей в классы. Я оставил комментарий.
> 4. Не при каждом вызове api есть обработка исключений
> 
> И да, не забывай, пожалуйста, указывать в README ссылку на текущий PR
> 
> Поправь эти моменты и двинемся дальше :)

Исправил замечания, в тестах добавил beforeEach, но теперь валится последний тест, не понимаю почему.

2022-04-29 18:52 UTC, agadoev commented
Привет)
Спасибо за правки,  я добавил еще несколько наблюдений, на которые стоит обратить внимание. Они не слишком критичные, но лучше тебе их исправить. 
Я посмотрел, что ты сделал с сервисами, это не совсем синглтон, но уже значительно лучше чем то, что было в первом варианте. На самом деле сервисы не всегда должны быть синглтонами, и кто-то даже считает синглтон антипаттерном)
Насчет переимнования AuthAPI в authAPI - если ругается IDE - просто перезапусти ее, скорее всего там лагает IntelliSense. Тест падает точно не из-за этого

Работу принимаю, удачи в дальнейшем)

2022-04-30 07:53 UTC, merged